### PR TITLE
Update function.ts

### PR DESCRIPTION
**Pull request by zdc1111**
fix: Delete redundant code

### Description
fix(function.ts) Delete-redundant-cod

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Enhancement (changes that improvement of current feature or performance)
- [ ] Refactoring (changes that neither fixes a bug nor adds a feature)
- [ ] Test Case (changes that add missing tests or correct existing tests)
- [ ] Code style optimization (changes that do not affect the meaning of the code)
- [ ] Docs (changes that only update documentation)
- [ ] Chore (changes that don't modify src or test files)

### Self Check before Merge

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [**CONTRIBUTING**](https://github.com/antvis/x6/blob/master/CONTRIBUTING.md) document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by bubkoo** [comment]
image
编译之后的代码使用了 apply，所以这里还不能这么改

**Comment by zdc1111** [comment]
> image
> 编译之后的代码使用了 apply，所以这里还不能这么改

实在不好意思  下次提交代码我会关注一下成果物   那我用switch 来替换if吧

**Comment by bubkoo** [comment]
@zdc1111 switch 替换 if 是处于什么考虑

**Comment by zdc1111** [comment]
> @zdc1111 switch 替换 if 是出于什么考虑

如果 入参长度为6的话 if需要判断多次if  else 直到匹配到 6 为止
image

**Comment by zdc1111** [comment]
@bubkoo 你觉得这样改可以吗

**Comment by bubkoo** [comment]
> @bubkoo 你觉得这样改可以吗

@zdc1111 可以啊

**Pull request merged**
