### PR TITLE
fix: ref cache cause error

### PR DESCRIPTION
**Pull request by codinglobster**
### Description

ref cache cause error, so remove it.

### Motivation and Context
image

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Enhancement (changes that improvement of current feature or performance)
- [ ] Refactoring (changes that neither fixes a bug nor adds a feature)
- [ ] Test Case (changes that add missing tests or correct existing tests)
- [ ] Code style optimization (changes that do not affect the meaning of the code)
- [ ] Docs (changes that only update documentation)
- [ ] Chore (changes that don't modify src or test files)

### Self Check before Merge

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING**](https://github.com/antvis/x6/blob/master/CONTRIBUTING.md) document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Review by NewByVector — COMMENTED** [review]
Can you provide a reproducible demo？

**Comment by codinglobster** [comment]
> Can you provide a reproducible demo？

https://x6.antv.antgroup.com/examples/showcase/practices#flowchart

you could just resize the *polygon* base shapes, right after page crashed. data are cached, but functions are not.

**Comment by NewByVector** [comment]
The source cause of the error here is the `Dom.data`, I fix it in https://github.com/antvis/X6/pull/2954

**Review by NewByVector — CHANGES_REQUESTED** [review]
The source cause of the error here is the Dom.data, I fix it in https://github.com/antvis/X6/pull/2954

**Pull request closed without merging**
