### PR TITLE
fix: :bug: char ghosting when edit text (#2560)

### PR DESCRIPTION
**Pull request by njshuisheng**
### Description

edit status char ghosting.

clear display value when edit status because char ghosting.

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Enhancement (changes that improvement of current feature or performance)
- [ ] Refactoring (changes that neither fixes a bug nor adds a feature)
- [ ] Test Case (changes that add missing tests or correct existing tests)
- [ ] Code style optimization (changes that do not affect the meaning of the code)
- [ ] Docs (changes that only update documentation)
- [ ] Chore (changes that don't modify src or test files)

### Self Check before Merge

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [**CONTRIBUTING**](https://github.com/antvis/x6/blob/master/CONTRIBUTING.md) document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Review by NewByVector — COMMENTED** [review]
In what scenarios does char ghosting occur?

**Comment by njshuisheng** [comment]
image
image
[https://github.com/antvis/X6/issues/2560](url)

**Review by NewByVector — CHANGES_REQUESTED** [review]
Your solution does solve the ghost problem,There are two small improvements:
1. Add a determination of whether setText is a function
2. The setText is extracted from the common method because the file uses the same functionality in two places

**Review by njshuisheng — COMMENTED** [review]
That's right

**Review by NewByVector — APPROVED** [review]

**Pull request merged**
