### PR TITLE
fix: 🐛 add some case sensitive attr

### PR DESCRIPTION
**Pull request by NewByVector**
### Description

增加常见的大小写敏感属性：

```ts
const CASE_SENSITIVE_ATTR = [
  'viewBox',
  'attributeName',
  'attributeType',
  'repeatCount',
]
```

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Enhancement (changes that improvement of current feature or performance)
- [ ] Refactoring (changes that neither fixes a bug nor adds a feature)
- [ ] Test Case (changes that add missing tests or correct existing tests)
- [ ] Code style optimization (changes that do not affect the meaning of the code)
- [ ] Docs (changes that only update documentation)
- [ ] Chore (changes that don't modify src or test files)

### Self Check before Merge

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [**CONTRIBUTING**](https://github.com/antvis/x6/blob/master/CONTRIBUTING.md) document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by tonywu6** [comment]
这里不如直接把 MDN 上所有列出的混合大小写的 attributes 一次性加进来？不然之后可能还会有新的 issues

```js
// https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute
const MIXED_CASE_SVG_ATTRIBUTES = new Set([
  'attributeName',
  'attributeType',
  'baseFrequency',
  'baseProfile',
  'calcMode',
  'clipPathUnits',
  'contentScriptType',
  'contentStyleType',
  'diffuseConstant',
  'edgeMode',
  'filterRes',
  'filterUnits',
  'glyphRef',
  'gradientTransform',
  'gradientUnits',
  'kernelMatrix',
  'kernelUnitLength',
  'keyPoints',
  'keySplines',
  'keyTimes',
  'lengthAdjust',
  'limitingConeAngle',
  'markerHeight',
  'markerUnits',
  'markerWidth',
  'maskContentUnits',
  'maskUnits',
  'numOctaves',
  'pathLength',
  'patternContentUnits',
  'patternTransform',
  'patternUnits',
  'pointsAtX',
  'pointsAtY',
  'pointsAtZ',
  'preserveAlpha',
  'preserveAspectRatio',
  'primitiveUnits',
  'referrerPolicy',
  'refX',
  'refY',
  'repeatCount',
  'repeatDur',
  'requiredExtensions',
  'requiredFeatures',
  'specularConstant',
  'specularExponent',
  'spreadMethod',
  'startOffset',
  'stdDeviation',
  'stitchTiles',
  'surfaceScale',
  'systemLanguage',
  'tableValues',
  'targetX',
  'targetY',
  'textLength',
  'viewBox',
  'viewTarget',
  'xChannelSelector',
  'yChannelSelector',
  'zoomAndPan',
])
```

**Comment by NewByVector** [comment]
@tonywu6 其他看起来不常见，先用遇到一个增加一个的策略。

**Comment by HQidea** [comment]
@NewByVector 我想控制节点里面的文字可以自适应容器大小，需要用到textLength和lengthAdjust属性，可以增加到这个大小写敏感属性的列表里吗？

**Comment by NewByVector** [comment]
@HQidea 提个 PR ？

**Comment by bighhhh** [comment]
> @tonywu6 其他看起来不常见，先用遇到一个增加一个的策略。

这一个一个提太麻烦了

**Comment by bighhhh** [comment]
preserveAspectRatio属性加入CASE_SENSITIVE_ATTR白名单

**Comment by JoeWrights** [comment]
> @tonywu6 其他看起来不常见，先用遇到一个增加一个的策略。

大佬，可否增加一个全局配置入口

**Pull request merged**
