### PR TITLE
fix: 🐛 fix type errors

### PR DESCRIPTION
**Pull request by bubkoo**
fix type errors in ci

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Enhancement (changes that improvement of current feature or performance)
- [x] Refactoring (changes that neither fixes a bug nor adds a feature)
- [ ] Test Case (changes that add missing tests or correct existing tests)
- [x] Code style optimization (changes that do not affect the meaning of the code)
- [ ] Docs (changes that only update documentation)
- [ ] Chore (changes that don't modify src or test files)

### Self Check before Merge

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING**](https://github.com/antvis/x6/blob/master/CONTRIBUTING.md) document.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Review by NewByVector — APPROVED** [review]

**Review by NewByVector — CHANGES_REQUESTED** [review]
ci 报错了

**Comment by bubkoo** [comment]
> ci 报错了

就是在修 CI 报错问题

**Comment by bubkoo** [comment]
什么情况，怎么修都修不了，崩溃

**Comment by OpportunityLiu** [comment]
这为啥要定义成 `any` 啊

image

image

image

**Comment by OpportunityLiu** [comment]
image
这也变成 `any` 了

**Pull request merged**
