### PR TITLE
The Nodes can align by port position

### PR DESCRIPTION
**Pull request by lyon-liao**
### Description
There is an [issue](https://github.com/antvis/X6/issues/3077), we have discussed the feature.  This is my first PR, if I made some mistakes please let me know. 

**Changes**
- Changed the `snapline example`
- Added some code to `x6-plugin-snapline` to achieve this feature.

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Enhancement (changes that improvement of current feature or performance)
- [ ] Refactoring (changes that neither fixes a bug nor adds a feature)
- [ ] Test Case (changes that add missing tests or correct existing tests)
- [ ] Code style optimization (changes that do not affect the meaning of the code)
- [ ] Docs (changes that only update documentation)
- [ ] Chore (changes that don't modify src or test files)

### Self Check before Merge

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING**](https://github.com/antvis/x6/blob/master/CONTRIBUTING.md) document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Review by NewByVector — CHANGES_REQUESTED** [review]
In order to be compatible with the previous feature, this feature should be enabled with a new configuration.

**Comment by lyon-liao** [comment]
@NewByVector I have changed the code, I added a `byPort` property in the `SnaplineImpl.Options`, and I changed the document.

Do you think I need to add some code to show how to disable and enable the feature in the example? For now, I didn't do it. the example looks like the following image.

image

**Comment by lyon-liao** [comment]
I have a new idea. I don't want to align by port now, I think we can check whether the port has a line, if that, we can align the node by this port position and the nearest point on the line. By doing that the user can easily align the line and port. and have some other advantages.
- No need to scan all ports to improve performance.
- Connecting lines and ports are orthogonal.

@NewByVector  Do you think so, if so, I will refactor this feature.

**Comment by NewByVector** [comment]
@lyon-liao I don't understantd `the port has a line`，can you explain it?

**Comment by lyon-liao** [comment]
image

If a line connects to a port, I think we can change the node position by points A and B.

**Comment by NewByVector** [comment]
@lyon-liao But a line doesn't have to be a straight line.

**Comment by lyon-liao** [comment]
@NewByVector Yes, A line doesn't have to be a straight line. we can use the `tolerance`. if the `diffX` or `diffY` less than `tolerance`, we can change the node position to make sure the line segment is horizontal and vertical.

**Comment by NewByVector** [comment]
@lyon-liao I'm sorry that I haven't understood your new scheme yet. Could you please explain it more clearly?

**Comment by lyon-liao** [comment]
image
@NewByVector I'm sorry I didn't express it clearly. As the image shows, if the `dx` or `dy`  is not 0, and it's value less than `tolerance `. we can change the node position to make two points(A and B) horizontal.

**Comment by NewByVector** [comment]
In fact, it is not necessary to judge according to the line, but according to the central point coordinates of the two nodes to judge, if the central point coordinates of the two nodes cannot be aligned, it needs to make some corrections. Is my understanding correct?

**Comment by lyon-liao** [comment]
image

@NewByVector 不是，通常我们需要移动Node 来确保跟Port 连接的线段能够保持水平或垂直（是线段能水平或垂直），如果只靠鼠标移动节点来实现的话，其实是比较困难的，尤其是旁边还有Node的时候，如果旁边有Node 可能会触发Node 之间的对齐机制，这样就可能跳过能让线水平的位置。我们希望线的连接是横平竖直的，这样看起来要工整一些。所以我希望在Node 移动的过程中我们添加另外一种对齐机制，检查被拖拽节点的所有Port, 如果Port 连接了线，并且port 相对画布的位置和线上以之相邻的那个点(记为A)如果存在`dx` 或 `dy` 小于参数`tolerance`。那么我们将调整被拖拽的Node 的位置使这个port 和点A 水平或竖直对齐。

**Comment by NewByVector** [comment]
@lyon-liao A 点怎么确定呢？

**Comment by lyon-liao** [comment]
> @lyon-liao A 点怎么确定呢？

这里会有两种情况
1. Port 直连了另外一个Port（记为P）， 此时 A 点就应该是Port P 的位置坐标。
2. Port 连接的（多）线段，此时根据port 是line 的source还是target 从而确定是line 的头还是尾连接的port. 如果是头连接port 的话A 点就是line.getVertices()[0]

**Comment by NewByVector** [comment]
@lyon-liao 对这一块还是有疑问，方便加钉钉交流(vectorse) 吗？

**Comment by lyon-liao** [comment]
有新的实现方案。

**Pull request closed without merging**
