### PR TITLE
Update function.ts

### PR DESCRIPTION
**Pull request by zdc1111**
fix: remove redundant code

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Enhancement (changes that improvement of current feature or performance)
- [ ] Refactoring (changes that neither fixes a bug nor adds a feature)
- [ ] Test Case (changes that add missing tests or correct existing tests)
- [ ] Code style optimization (changes that do not affect the meaning of the code)
- [ ] Docs (changes that only update documentation)
- [ ] Chore (changes that don't modify src or test files)

### Self Check before Merge

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [**CONTRIBUTING**](https://github.com/antvis/x6/blob/master/CONTRIBUTING.md) document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by bubkoo** [comment]
@zdc1111 
根据参数数量 `call` 还是 `apply` 是出于性能考虑，参考：https://stackoverflow.com/a/33054992

**Comment by zdc1111** [comment]
@bubkoo 
多谢解惑 ， 那为什么 入参长度小于等于6时候 call 不使用解构而是 写那么多个if呢？    考虑解构的性能问题？

**Comment by bubkoo** [comment]
> @bubkoo
> 多谢解惑 ， 那为什么 入参长度小于等于6时候 call 不使用解构而是 写那么多个if呢？ 考虑解构的性能问题？

这里可以按照你的思路优化，有时间修改一下，我来 merge

**Comment by afc163** [comment]
@zdc1111 贡献代码的机会来了

**Pull request closed without merging**
