### PR TITLE
fix: optimize snapToGrid options for manhattan

### PR DESCRIPTION
**Pull request by NewByVector**
### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Enhancement (changes that improvement of current feature or performance)
- [ ] Refactoring (changes that neither fixes a bug nor adds a feature)
- [ ] Test Case (changes that add missing tests or correct existing tests)
- [ ] Code style optimization (changes that do not affect the meaning of the code)
- [ ] Docs (changes that only update documentation)
- [ ] Chore (changes that don't modify src or test files)

### Self Check before Merge

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [**CONTRIBUTING**](https://github.com/antvis/x6/blob/master/CONTRIBUTING.md) document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by CupNoodleFork** [comment]
@NewByVector 最后一个点，前一个点之间的比较，看着会出现 x 既不相等，y 也不相等的情况。

**Comment by NewByVector** [comment]
@CupNoodleFork 有场景看下吗？

**Comment by CupNoodleFork** [comment]
起始点的坐标，假如用户确定了是在某一个边的中心点，看着好像也会被吸附到网格线上？

**Comment by CupNoodleFork** [comment]
> @CupNoodleFork 有场景看下吗？
@NewByVector 这个理解有误，没什么问题。就是上面那个情况，会导致起始和结束的锚点位置产生变化。

**Pull request merged**
