### PR TITLE
chore: support TypeScript 4

### PR DESCRIPTION
**Pull request by CarterLi**
### Description

兼容 ts4+

### Motivation and Context

修复ts4报错

```
node_modules/@antv/x6/lib/geometry/path/close.d.ts(4,9):
4:9 'end' is defined as a property in class 'Segment', but is overridden here in 'Close' as an accessor.
    2 | import { Segment } from './segment';
    3 | export declare class Close extends Segment {
  > 4 |     get end(): Point;
      |         ^
    5 |     get type(): string;
    6 |     bbox(): any;
    7 |     closestPoint(p: Point | Point.PointLike | Point.PointData): any;
```

我本来想把 Segment 的 end 属性定义改成 getter，但是看到其他 Segment 的子类都直接给 end 赋值了，简单起见就直接把 ts 的报错忽略掉

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Enhancement (changes that improvement of current feature or performance)
- [ ] Refactoring (changes that neither fixes a bug nor adds a feature)
- [ ] Test Case (changes that add missing tests or correct existing tests)
- [ ] Code style optimization (changes that do not affect the meaning of the code)
- [ ] Docs (changes that only update documentation)
- [ ] Chore (changes that don't modify src or test files)

### Self Check before Merge

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [**CONTRIBUTING**](https://github.com/antvis/x6/blob/master/CONTRIBUTING.md) document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by CarterLi** [comment]
如果能合并的话求发个 4.9 版本，求关照前期采坑用户😢

**Comment by bubkoo** [comment]
> 如果能合并的话求发个 4.9 版本，求关照前期采坑用户😢

是要 0.4.9 版本吧

**Comment by CarterLi** [comment]
> > 如果能合并的话求发个 4.9 版本，求关照前期采坑用户😢
> 
> 是要 0.4.9 版本吧

手抖。。。

**Comment by bubkoo** [comment]
@CarterLi v0.4.9 可用了

**Comment by CarterLi** [comment]
卧槽，生成 close.d.ts 后 @ts-ignore 注释没了 😭

**Pull request merged**
