### PR TITLE
feat: Update Angular Lib provide data to the Angular Template

### PR DESCRIPTION
**Pull request by lukaswork**
I added in my own Copy of this Angular Lib this Piece to give through the node data to the rendered html template. My interesting also for others?

In Angular you could access then the Data like this:
<ng-template #template let-data="data">
...
</ng-template>

### Description

Adding the Context from the node Data to the Angular Template

### Motivation and Context

Implemented in my own Project like this

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] Enhancement (changes that improvement of current feature or performance)
- [ ] Refactoring (changes that neither fixes a bug nor adds a feature)
- [ ] Test Case (changes that add missing tests or correct existing tests)
- [ ] Code style optimization (changes that do not affect the meaning of the code)
- [ ] Docs (changes that only update documentation)
- [ ] Chore (changes that don't modify src or test files)

### Self Check before Merge

- [ ] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [**CONTRIBUTING**](https://github.com/antvis/x6/blob/master/CONTRIBUTING.md) document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Review by bubkoo — APPROVED** [review]

**Comment by NewByVector** [comment]
@Eve-Sama  帮忙 review 一下这个 PR

**Comment by Eve-Sama** [comment]
你好, 最近工作比较忙, 暂时无法为你review, 我预计本周末或下周末为你review.

如你想要立刻获得该PR支持, 你可以参考下一个[demo仓库 ](https://github.com/Eve-Sama/ngx-x6-demo) 因为`x6-angular-shape`是扩展了X6, 而不是直接修改X6可视化引擎底层的. 所以你也完全可以把该部分源码放在你自己的项目内部. 

再次感谢你提的这个PR, 这非常有价值.

**Comment by Eve-Sama** [comment]
本地测试了下, 存在以下问题.
第一, 不必判断node.data是否存在. 因为node一定是存在的, 所以node.data这句话最多只是个null. 而`TemplatePortal`的构造函数声明如下
`new TemplatePortal<{}>(template: TemplateRef<{}>, viewContainerRef: ViewContainerRef, context?: {} | undefined): TemplatePortal<{}>`
所以, `context`是可以为空的, 直接传递node.data就可以了. 
第二, `ComponentPortal`不应该传递node.data, 因为他的构造函数为
`new ComponentPortal<any>(component: ComponentType<any>, viewContainerRef?: ViewContainerRef | null | undefined, injector?: Injector | null | undefined, componentFactoryResolver?: ComponentFactoryResolver | ... 1 more ... | undefined): ComponentPortal<...>`
从定义上看, 第三个参数是`Injector`而不是一个普通对象. 你可以参考下[zorro](https://github.com/NG-ZORRO/ng-zorro-antd)的`nzComponentParams`是如何传递给组件的.

**Comment by Eve-Sama** [comment]
关于在组件渲染的场景下, 我确实也不了解应该如何传递参数给组件(不是template), 你的这个写法, 不会报错, 但是我想了解下在你的这个写法下`new ComponentPortal(content, viewContainerRef, node.data)`, 这个组件如何拿到data呢?

**Comment by lukaswork** [comment]
Unfortunatly I couldn't get the ComponentPortal to work, I just used the TemplateRef all the time to access my data.
By just researching and trying out, it kinda works with a injector in Front.
Maybe you have a hint how to get the Component Portal to work?

**Comment by Eve-Sama** [comment]
Sorry, I thought you were Chinese. I think the most important thing is to help you to figure out the problem. First of all, can you tell me if the `TemplateRef` is the only one you need?

**Comment by Eve-Sama** [comment]
This PR should be closed. @NewByVector

**Pull request closed without merging**
