### PR TITLE
fix: trigger dblclick event only one time

### PR DESCRIPTION
**Pull request by NewByVector**
### Description

Close https://github.com/antvis/X6/issues/3575 https://github.com/antvis/X6/issues/3559

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Enhancement (changes that improvement of current feature or performance)
- [ ] Refactoring (changes that neither fixes a bug nor adds a feature)
- [ ] Test Case (changes that add missing tests or correct existing tests)
- [ ] Code style optimization (changes that do not affect the meaning of the code)
- [ ] Docs (changes that only update documentation)
- [ ] Chore (changes that don't modify src or test files)

### Self Check before Merge

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [**CONTRIBUTING**](https://github.com/antvis/x6/blob/master/CONTRIBUTING.md) document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by hylerrix** [comment]
@NewByVector [这个改动在 1.x 版本也遇到了，可以将 pr 也更新到 v1.x 版本中吗？](https://github.com/antvis/X6/issues/3575#issuecomment-1632284747)

我看 PR 里的相关改动，在 v1 里代码非常不一样，所以让我来的话我也不知道从何下手。

**Comment by NewByVector** [comment]
@hylerrix 可以把 cell-editor 的源码拉出来，自定义自己的工具。使用方式和 2.x 对齐。

**Comment by hylerrix** [comment]
> @hylerrix 可以把 cell-editor 的源码拉出来，自定义自己的工具。使用方式和 2.x 对齐。

感谢提醒，那也就是 x6 官方不准备在 v1.x 中修补了？

**Comment by NewByVector** [comment]
@hylerrix 使用方式不太一样，如果修改是 break change，所以不准不准在 1.x 中修改了。

**Pull request merged**
