### PR TITLE
feat: add snapToGrid options for manhattan router

### PR DESCRIPTION
**Pull request by NewByVector**
### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Enhancement (changes that improvement of current feature or performance)
- [ ] Refactoring (changes that neither fixes a bug nor adds a feature)
- [ ] Test Case (changes that add missing tests or correct existing tests)
- [ ] Code style optimization (changes that do not affect the meaning of the code)
- [ ] Docs (changes that only update documentation)
- [ ] Chore (changes that don't modify src or test files)

### Self Check before Merge

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [**CONTRIBUTING**](https://github.com/antvis/x6/blob/master/CONTRIBUTING.md) document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by CupNoodleFork** [comment]
2.1.0 版本不增加 `snapToGrid: false` 参数存在问题。
https://codesandbox.io/s/wild-sea-4lpnyz?file=/index.ts
image

**Comment by NewByVector** [comment]
@CupNoodleFork 在 2.1.1 版本中将 snapToGrid 默认设置为 `false`

**Comment by CupNoodleFork** [comment]
@NewByVector "连接线的顶点对齐网格"，我觉得这个点没有问题。但是我觉得应该要保证 `manhattan` 算法所描述的连接线是 水平&垂直的正交线段。比如上面我展示错误用例的图中，2到3的连接线，起始点2的下一个连接点需要对齐网格，但是这个点的 y 需要和起始点保持一致，调整x坐标对齐网格，保证这一线段是水平的。我个人感觉要是用户去调整节点尺寸，来保证连线对齐网格，理解成本和心智负担有点多。

**Comment by NewByVector** [comment]
@CupNoodleFork 有道理，感觉还可以优化一波，我修改下。

**Pull request merged**
