### PR TITLE
fix: 🐛 support css var in font-size

### PR DESCRIPTION
**Pull request by NewByVector**
### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Enhancement (changes that improvement of current feature or performance)
- [ ] Refactoring (changes that neither fixes a bug nor adds a feature)
- [ ] Test Case (changes that add missing tests or correct existing tests)
- [ ] Code style optimization (changes that do not affect the meaning of the code)
- [ ] Docs (changes that only update documentation)
- [ ] Chore (changes that don't modify src or test files)

### Self Check before Merge

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [**CONTRIBUTING**](https://github.com/antvis/x6/blob/master/CONTRIBUTING.md) document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by OpportunityLiu** [comment]
其实还有`calc` `min` `max`啥的吧

**Comment by OpportunityLiu** [comment]
而且，说到底 style attribute 也还是 attribute，所以其实还有更离谱的操作

`<text font-size="xxx">`

```css
[font-size=xxx] {
    font-size: 12px;
}
```

（其实最近刚干出差不多的事情
image

**Comment by NewByVector** [comment]
@OpportunityLiu 其实是不推荐使用 css 变量或者其他操作的。因为设置 text 的时候，要根据实际字体大小来决定换行等问题。如果不是数字，换行、wrap 等功能是不准确的(按照 16px来计算的)

**Comment by OpportunityLiu** [comment]
我的主题系统就是基于 css 变量的，设实际值反而很麻烦

**Comment by NewByVector** [comment]
@OpportunityLiu 这样吧 我还原之前的逻辑 只要 font-size 传了值，原样输出。

**Comment by OpportunityLiu** [comment]
image
这不挺准？我看代码里也是用 `getComputedTextLength` 量出来的啊

https://github.com/antvis/X6/blob/f9fef32674b4596a85f2ac3544ade8bf07f7f85f/packages/x6/src/util/dom/text.ts#L681

**Comment by OpportunityLiu** [comment]
好像只有在设了 `TextOptions["annotations"]` 的时候才会用 font-size 做 base size，计算当前行最大字号的 px，决定行高，设置下一行的偏移位置，然后这玩意也是 undocumented

**Pull request merged**
