### PR TITLE
update github issue templates

### PR DESCRIPTION
**Pull request by cliffordfajardo**
## What is the change?
1. Update the `bug_report.yml` github file to enable [Github's new issue template form](https://youtu.be/qQE1BUkf2-s?t=23)
2. Add `config.yml` inside file the `.github/ISSUE_TEMPLATE/` folder
3. Update `feature_request.md` to `feature_request.yml`

## Motivation for this code change?
- encourage's bug reporter's to put more care into their bug report before submission
- this may help `X6` maintainer's receive more detailed & higher quality bug report's
- prevents bug reporter from submitting a bug IF they do not fill in the required fields specified in the `bug_report.yml` file
- adds helpful tips for user's during the process of creating a bug/issue report
- encourages community to ask question's inside of [X6's Discussion tab](https://github.com/antvis/X6/discussions)
- [G6 recently has added these changes](https://github.com/antvis/G6/pull/3364)
- [Graphin recently has added these changes](https://github.com/antvis/Graphin/pull/338)

## Example / Demo:
- Demo repository: https://github.com/cliffordfajardo/test-x6-github-issue-template/issues/new/choose
CleanShot 2021-12-17 at 11 12 37

**Issue template example :**
CleanShot 2021-12-17 at 11 13 18

## References
- [Github Docs for templates to encourage useful issues & pull requests](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-issue-forms) 
- [Github Docs for `config.yml` file](https://docs.github.com/en/enterprise-server@3.0/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository#configuring-the-template-chooser)

### CODE REVIEW

**Comment by cliffordfajardo** [comment]
@NewByVector

**Review by NewByVector — CHANGES_REQUESTED** [review]
The Chinese translation is not reasonable, you can submit the English version first.

**Comment by cliffordfajardo** [comment]
@NewByVector - ok sounds good

**Comment by cliffordfajardo** [comment]
@NewByVector  - removed the Chinese translations

**Comment by cliffordfajardo** [comment]
@NewByVector - I also added translations for `@antv/XFlow` (react based version of G6)
- https://github.com/antvis/X6/pull/1658

**Comment by NewByVector** [comment]
@cliffordfajardo Thanks, Great PR!

**Pull request merged**
