### PR TITLE
解决高亮效果不跟随移动问题

### PR DESCRIPTION
**Pull request by NewByVector**
### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Enhancement (changes that improvement of current feature or performance)
- [ ] Refactoring (changes that neither fixes a bug nor adds a feature)
- [ ] Test Case (changes that add missing tests or correct existing tests)
- [ ] Code style optimization (changes that do not affect the meaning of the code)
- [ ] Docs (changes that only update documentation)
- [ ] Chore (changes that don't modify src or test files)

### Self Check before Merge

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [**CONTRIBUTING**](https://github.com/antvis/x6/blob/master/CONTRIBUTING.md) document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by bubkoo** [comment]
什么情况下 highlight 需要动态移动，有案例吗

**Comment by NewByVector** [comment]
> 什么情况下 highlight 需要动态移动，有案例吗

调用 highlight 方法去高亮一个边或者节点。移动的时候高亮不随着移动。 我是想 既然 hightlight方法暴露出来，是否需要支持随着节点或者边移动

**Comment by NewByVector** [comment]
这个在实际场景中还没遇到过问题， pr 先不合？

**Comment by bubkoo** [comment]
手动调用highlight会出现你说的问题，但是这个API应该很少被用到，highlight基本上是为交互设计的，交互过程中highlight结束后就自动取消了。
可以先放一放，多思考一会再来讨论一下看看

**Comment by NewByVector** [comment]
无业务需求，暂时关闭

**Pull request closed without merging**
